[project]
name = "deltabot-telegram-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deltachat2[full]>=0.9.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "telethon>=1.42.0",
]
